// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QLNS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230521140813_Create_Table_Hopdong")]
    partial class Create_Table_Hopdong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("QLNS.Models.Hopdong", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ngaybatdau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ngayketthuc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaNV");

                    b.ToTable("Hopdong");
                });

            modelBuilder.Entity("QLNS.Models.Nhansu", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chucvu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaNV");

                    b.HasIndex("MaPhong");

                    b.ToTable("Nhansu");
                });

            modelBuilder.Entity("QLNS.Models.Phongban", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPhong");

                    b.ToTable("Phongban");
                });

            modelBuilder.Entity("QLNS.Models.Nhansu", b =>
                {
                    b.HasOne("QLNS.Models.Phongban", "TenPhong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenPhong");
                });
#pragma warning restore 612, 618
        }
    }
}
